-- Upgrade 1.1.0 -> 1.2.0. Apply once as project postgres/migration administrator.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';
SET LOCAL ROLE eas_migration;

REVOKE ALL ON FUNCTION mock_assets.guard_loan_overlap() FROM PUBLIC;
REVOKE ALL ON FUNCTION mock_facilities.guard_reservation_overlap() FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE eas_migration IN SCHEMA mock_hr REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE eas_migration IN SCHEMA mock_assets REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE eas_migration IN SCHEMA mock_facilities REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE eas_migration IN SCHEMA mock_crm REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE eas_migration IN SCHEMA mock_procurement REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE eas_migration IN SCHEMA mock_it REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE eas_migration IN SCHEMA mock_finance REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE eas_migration IN SCHEMA mock_travel REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

INSERT INTO mock_hr.schema_migration(version,description)
VALUES ('002','Least-privilege function defaults');
COMMIT;
